version: '3'

services:
  db:
    container_name: mysql8-hillel
    image: mysql:8.0
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog
      MYSQL_USER: blog
      MYSQL_PASSWORD: blog
      MUSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
